name: Angular PROD CI & Deploy

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build-deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test -- --watch=false

      - name: Build PROD app
        run: npm run build:prod

      - name: Configure git identity
        run: |
          git config --global user.name "santoshmattikoppa"
          git config --global user.email "santoshmattikoppa@gmail.com"

      - name: Deploy PROD to GitHub Pages
        run: |
          npx gh-pages \
            -d dist/my-angular-app/browser \
            -b gh-pages \
            -r https://x-access-token:${GITHUB_TOKEN}@github.com/santoshmattikoppa/My-Angular-app.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
